/* Generated By:JavaCC: Do not edit this line. LambdaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LambdaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LAMBDA = 2;
  /** RegularExpression Id. */
  int DOT = 3;
  /** RegularExpression Id. */
  int OPEN = 4;
  /** RegularExpression Id. */
  int CLOSE = 5;
  /** RegularExpression Id. */
  int VAR = 6;
  /** RegularExpression Id. */
  int EXPR = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\"^\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "<VAR>",
    "<EXPR>",
    "\"==\"",
  };

}
